name: Build FFGBSY Server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: "6.0.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore --output ./dist

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Application
          path: ./dist
